### ISSUE TITLE
Remove props from interior?

### ISSUE THREAD

**Issue by spcckz** [Starystars67/Titch2000_Arena#1]
Hey! my original plan was to post on your post in the FiveM forums but it looks like you're more active here on GitHub. Is there any way to remove props from the interior of the arena? All i want is the dirt part of the map in the middle, the garages, crowd, and the rest of the building surrounding it. I've tried editing the code but it really doesn't seem to do much for it. My plan is to build my own course for a monster truck arena. Thanks!

**Comment by Starystars67** [comment]
Hey! I assume non of the maps that come with the game suited your needs?
If they did not then the next option would to be to have to modify one of the maps that is close to your liking. This can be done in in codewalker and or 3ds max depending on how the map is made up.

I do not remember where the files are located within the game though so you will have to do some digging around in OpenIV to find them.

Hope this helps. Feel free to comment back of course!

**Comment by spcckz** [comment]
> This can be done in in codewalker and or 3ds max depending on how the map is made up.
> 
Absolutely! Sounds easy enough, I actually dabble in 3DS max here and there and am currently working on converting a map! Duh! Should have thought about that one. 

May not be the place to ask, But if you know anything about map conversions and you felt up to helping me, i'd really appreciate it! Just say the word and i'll shoot you my discord or something so it's easier to chat. Thanks =]

**Comment by Starystars67** [comment]
Sorry but I do not know anything about map conversions no. Going back to the editing of the map you will likely have to edit 2 parts. One of them is the collisions and the other is the visual part. Be sure to do both!
